In [40]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [41]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target,test_size=0.3)

In [42]:
lr = LogisticRegression(max_iter=3000)
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9592592592592593

In [43]:
svm = SVC(max_iter=2000)
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.987037037037037

In [44]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9740740740740741

In [45]:
from sklearn.model_selection import KFold
k_fold = KFold(n_splits=3)

In [46]:
for train_index, test_index in k_fold.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [47]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [48]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [49]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index, test_index in k_fold.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]

    scores_l.append(get_score(LogisticRegression(max_iter=3000), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(max_iter=3000), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))

In [50]:
from sklearn.model_selection import cross_val_score

In [55]:
cross_val_score(RandomForestClassifier(n_estimators=999),digits.data,digits.target)

array([0.93611111, 0.91388889, 0.95821727, 0.9637883 , 0.9275766 ])